#!/bin/sh
set -e

. /rootfs/magento:entrypoint:template
. /rootfs/magento:setup:production
. /rootfs/magento:setup:crontab

# Clear Old Config and Env
echo "${DOCUMENT_ROOT}/bin/magento cache:flush"
"${DOCUMENT_ROOT}"/bin/magento cache:flush

echo "chmod -R 777 ${DOCUMENT_ROOT}/var/cache/*"
chmod -R 777 "${DOCUMENT_ROOT}"/var/cache/*