#!/bin/sh
set -e

wait_database_connection() {
    HOST_DOMAIN="host.docker.internal"

    if [ -z "${MAGENTO_DATABASE_PORT}" ]; then
        export MAGENTO_DATABASE_PORT=3306
    fi

    if [ -z "${MAGENTO_DATABASE_HOST}" ]; then
        export MAGENTO_DATABASE_HOST=${HOST_DOMAIN}
    fi

    until nc -z -v -w30 ${MAGENTO_DATABASE_HOST} ${MAGENTO_DATABASE_PORT}
    do
        echo "Waiting for database connection..."
        # wait for 5 seconds before check again
        sleep 5
    done
}

