#!/bin/sh
set -e

MAGENTO_ENV=${DOCUMENT_ROOT}/app/etc/env.php
MAGENTO_ENV_TEMPLATE=${DOCUMENT_ROOT}/app/etc/env.php.template

MAGENTO_CONFIG=${DOCUMENT_ROOT}/app/etc/config.php
MAGENTO_CONFIG_TEMPLATE=${DOCUMENT_ROOT}/app/etc/config.php.template

# Copy Config
if [ -f "${MAGENTO_CONFIG_TEMPLATE}" ]; then
    if [ ! -f "${MAGENTO_CONFIG}" ]; then
        echo "cp ${MAGENTO_CONFIG_TEMPLATE} ${MAGENTO_CONFIG}"
        cp "${MAGENTO_CONFIG_TEMPLATE}" "${MAGENTO_CONFIG}"
    fi
fi

# Wait for Env
while [ ! -f "${MAGENTO_ENV}" ]
do
		echo "Waiting for ${MAGENTO_ENV}..."
		if [ -f "${MAGENTO_ENV_TEMPLATE}" ]; then
        		echo "cp ${MAGENTO_ENV_TEMPLATE} ${MAGENTO_ENV}"
            cp "${MAGENTO_ENV_TEMPLATE}" "${MAGENTO_ENV}"
    fi
    sleep 2;
done