#!/bin/sh
set -e

if [ -f "${DOCUMENT_ROOT}"/composer.json ]; then
    echo "cd ${DOCUMENT_ROOT} && composer install"
    cd "${DOCUMENT_ROOT}" && composer install

    if [ "${MAGENTO_UPDATE_PACKAGE}" = true ]; then
        echo "composer update"
        composer update
    fi
else
    echo "We didn't find composer.json in ${DOCUMENT_ROOT}, please check it again."
fi


