#!/bin/sh
set -e

enable_developer_mode() {
    if [ -z "${MAGENTO_MODE}" ]; then
        MAGENTO_MODE="developer"
    fi

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/static/sign 0"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/static/sign 0

    echo "${DOCUMENT_ROOT}/bin/magento deploy:mode:set ${MAGENTO_MODE}"
    "${DOCUMENT_ROOT}"/bin/magento deploy:mode:set "${MAGENTO_MODE}"

    rm -rf "${DOCUMENT_ROOT}"/pub/static/frontend/* "${DOCUMENT_ROOT}"/pub/static/adminhtml/* \
    "${DOCUMENT_ROOT}"/var/cache/ "${DOCUMENT_ROOT}"/var/generation/ "${DOCUMENT_ROOT}"/var/page_cache/ \
    "${DOCUMENT_ROOT}"/var/view_preprocessed/ "${DOCUMENT_ROOT}"/var/composer_home "${DOCUMENT_ROOT}"/generated/*

    echo "${DOCUMENT_ROOT}/bin/magento cache:clean"
    "${DOCUMENT_ROOT}"/bin/magento cache:clean
}