#!/bin/sh
set -e

install_sampledata() {
    echo "Installing sampledata..."

    echo "cp /root/.composer/auth.json ${DOCUMENT_ROOT}/var/composer_home/auth.json"
    cp /root/.composer/auth.json "${DOCUMENT_ROOT}"/var/composer_home/auth.json

    echo "${DOCUMENT_ROOT}/bin/magento deploy:mode:set developer"
    "${DOCUMENT_ROOT}"/bin/magento deploy:mode:set developer

    install

    echo "${DOCUMENT_ROOT}/bin/magento setup:upgrade"
    "${DOCUMENT_ROOT}"/bin/magento setup:upgrade

    echo "Installed sampledata."
}

install() {
    echo "${DOCUMENT_ROOT}/bin/magento sampledata:deploy "
    "${DOCUMENT_ROOT}"/bin/magento sampledata:deploy
}

