#!/bin/sh
set -e

if [ -z "${MAGENTO_MINIFY_STATIC_FILE}" ]; then
    MAGENTO_MINIFY_STATIC_FILE=true
fi

if [ "${MAGENTO_MINIFY_STATIC_FILE}" = true ]; then
    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/js/enable_js_bundling 1"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/js/enable_js_bundling 1

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/js/minify_files 1"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/js/minify_files 1

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/js/merge_files 0"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/js/merge_files 0

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/css/minify_files 1"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/css/minify_files 1

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/css/merge_css_files 1"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/css/merge_css_files 1

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/template/minify_html 1"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/template/minify_html 1

    echo "${DOCUMENT_ROOT}/bin/magento config:set dev/static/sign 1"
    "${DOCUMENT_ROOT}"/bin/magento config:set dev/static/sign 1
fi

