#!/bin/sh
set -e

enable_developer_mode() {
    if [ -z "${MAGENTO_MODE}" ]; then
        MAGENTO_MODE="developer"
    fi

	echo "${DOCUMENT_ROOT}/bin/magento config:set dev/static/sign 0"
	"${DOCUMENT_ROOT}"/bin/magento config:set dev/static/sign 0

	echo "${DOCUMENT_ROOT}/bin/magento deploy:mode:set ${MAGENTO_MODE}"
	"${DOCUMENT_ROOT}"/bin/magento deploy:mode:set "${MAGENTO_MODE}"

	rm -rf "${DOCUMENT_ROOT}"/var/* "${DOCUMENT_ROOT}"/generated/*

	echo "${DOCUMENT_ROOT}/bin/magento cache:clean"
	"${DOCUMENT_ROOT}"/bin/magento cache:clean
}